# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Production flow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.13.0-chrome78-ff70
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          wait-on: http://localhost:3000

  # deploy-vercel:
  #   needs: [cypress-run]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Deploy to Vercel
  #       id: deploy-vercel-staging
  #       uses: amondnet/vercel-action@v20
  #       with:
  #         vercel-token: uFmdVbQ6Lx2gHR95pHCtJK4M
  #         vercel-org-id: qp2WInrcWswx79QwgVEiwwRV
  #         vercel-project-id: prj_xsyBdmPZu2xcgFSkNB4HyFZabjaW
  #         scope: qp2WInrcWswx79QwgVEiwwRV
